# WEEK 7 CONSOLIDATION TASK
# NUMBER GUESSING GAME - USING LOOPS

# This game will repeatedly prompt the user for inputs to guess a number between 1 and 10, which has been randomly generated by Python. 
# Using a loop structure, the programme repeatedly prompts the user for guesses until they guess the correct number or reach 8 attempts.

# Printing a fun decorative heading
print("┌" + "─" * 50 + "┐")
print("│" + "GUESS THE NUMBER!".center(50) + "│")
print("└" + "─" * 50 + "┘")
print("\nWelcome to the Number Guessing Game ")
print(" ")

# This imports the Python random module to generate a random number
import random

# The answer, stored as y, is a random integer between 1 and 10 inclusive.
y = random.randint(1, 10)
print("  ")

# This prompts the user for their guess, which is stored as an integer, x later in the script
print("Please guess a Number between 1 and 10 inclusive. You have EIGHT attempts\n")

# This creates a variable, attempts_left, and assigns it an initial value of 8. It will be used to count the number of guess attempt remaining
attempts_left = 8

# The boolean value, match, stores the fact that the user has not yet correctly guessed the number
match = False


# The WHILE keyword below creates a loop, which prompts the user for further input while the user has attempts remaining.
while attempts_left >= 1:
    x = input("Your Guess --> ").strip()
    # The below reduces the number of attempts left by one for each wrong guess, providing a termination condition
    attempts_left -= 1  

    # The below catches an exception where x is not a digit or where no input is entered
    # In this scenario, the user still uses up one attempt
    if not x.isdigit():
        print("Please enter a valid integer as input")
        print(f"You have {attempts_left} attempt(s) left. Try again.\n") # This prints the number of attempts left.
        print(" ")  # A blank line for neatness
        continue  # This returns to the start of the while loop above
    x = int(x)  # This converts x to an integer, where x is a digit

    # The below is implemented if the inputted number, x, is not the randomly-generated integer, y, and there are attempts remaining
    if x!= y and attempts_left > 0: 
        print(" ")  # A blank line for neatness
        print ("Wrong!")  
        print(f"You have {attempts_left} attempt(s) left. Try again.\n") # This prints the number of attempts left.

    # This is printed when the inputted number, x, matches the randomly-generated integer, y.
    if x == y: 
      print(" ")
      print("Correct!")
      match = True  # The boolean value, match, is amended to store the fact that the user has correctly gueesed the number
      break  # The loop breaks here and the programmes execution moves towards its end


# The below is triggered once there are 8 wrong guesses and the WHILE loop above breaks. It displays the correct answer
if attempts_left == 0:
    print(" ")  # A blank line for neatness
    print("Wrong!")
    print("You have guessed wrongly EIGHT times.")
    print(" ")  # A blank line for neatness
    print(f"The correct number is {y}.")
    print("The programme will now terminate. Try again later.")
    

# The below keeps the programme open until the user presses ENTER
print("\nThanks for playing")
stayopen = input("Press ENTER to exit...")
